// flow-typed signature: 689189c6666b48d2dda6ce03ca4215cb
// flow-typed version: <<STUB>>/@keenai/babel-preset-keenai_v^0.5.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@keenai/babel-preset-keenai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@keenai/babel-preset-keenai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@keenai/babel-preset-keenai/index' {
  declare module.exports: $Exports<'@keenai/babel-preset-keenai'>;
}
declare module '@keenai/babel-preset-keenai/index.js' {
  declare module.exports: $Exports<'@keenai/babel-preset-keenai'>;
}
